/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppEmployeeReviewsRouteImport } from './routes/_app.employee.reviews'
import { Route as AppEmployeeDashboardRouteImport } from './routes/_app.employee.dashboard'
import { Route as AppCustomerDashboardRouteImport } from './routes/_app.customer.dashboard'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminReviewsRouteImport } from './routes/_app.admin.reviews'
import { Route as AppAdminRequestsRouteImport } from './routes/_app.admin.requests'
import { Route as AppAdminEmployeesRouteImport } from './routes/_app.admin.employees'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin.dashboard'
import { Route as AppAdminCategoriesRouteImport } from './routes/_app.admin.categories'
import { Route as AppCustomerRequestsIndexRouteImport } from './routes/_app.customer.requests.index'
import { Route as AppEmployeeRequestsNearbyRouteImport } from './routes/_app.employee.requests.nearby'
import { Route as AppEmployeeRequestsIdRouteImport } from './routes/_app.employee.requests.$id'
import { Route as AppCustomerRequestsNewRouteImport } from './routes/_app.customer.requests.new'
import { Route as AppCustomerRequestsIdRouteImport } from './routes/_app.customer.requests.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeReviewsRoute = AppEmployeeReviewsRouteImport.update({
  id: '/employee/reviews',
  path: '/employee/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeDashboardRoute = AppEmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerDashboardRoute = AppCustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReviewsRoute = AppAdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRequestsRoute = AppAdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesRoute = AppAdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCategoriesRoute = AppAdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerRequestsIndexRoute =
  AppCustomerRequestsIndexRouteImport.update({
    id: '/customer/requests/',
    path: '/customer/requests/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEmployeeRequestsNearbyRoute =
  AppEmployeeRequestsNearbyRouteImport.update({
    id: '/employee/requests/nearby',
    path: '/employee/requests/nearby',
    getParentRoute: () => AppRoute,
  } as any)
const AppEmployeeRequestsIdRoute = AppEmployeeRequestsIdRouteImport.update({
  id: '/employee/requests/$id',
  path: '/employee/requests/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerRequestsNewRoute = AppCustomerRequestsNewRouteImport.update({
  id: '/customer/requests/new',
  path: '/customer/requests/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerRequestsIdRoute = AppCustomerRequestsIdRouteImport.update({
  id: '/customer/requests/$id',
  path: '/customer/requests/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/profile': typeof AppProfileRoute
  '/admin/categories': typeof AppAdminCategoriesRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/employees': typeof AppAdminEmployeesRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/reviews': typeof AppAdminReviewsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/customer/dashboard': typeof AppCustomerDashboardRoute
  '/employee/dashboard': typeof AppEmployeeDashboardRoute
  '/employee/reviews': typeof AppEmployeeReviewsRoute
  '/customer/requests/$id': typeof AppCustomerRequestsIdRoute
  '/customer/requests/new': typeof AppCustomerRequestsNewRoute
  '/employee/requests/$id': typeof AppEmployeeRequestsIdRoute
  '/employee/requests/nearby': typeof AppEmployeeRequestsNearbyRoute
  '/customer/requests/': typeof AppCustomerRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/profile': typeof AppProfileRoute
  '/admin/categories': typeof AppAdminCategoriesRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/employees': typeof AppAdminEmployeesRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/reviews': typeof AppAdminReviewsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/customer/dashboard': typeof AppCustomerDashboardRoute
  '/employee/dashboard': typeof AppEmployeeDashboardRoute
  '/employee/reviews': typeof AppEmployeeReviewsRoute
  '/customer/requests/$id': typeof AppCustomerRequestsIdRoute
  '/customer/requests/new': typeof AppCustomerRequestsNewRoute
  '/employee/requests/$id': typeof AppEmployeeRequestsIdRoute
  '/employee/requests/nearby': typeof AppEmployeeRequestsNearbyRoute
  '/customer/requests': typeof AppCustomerRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/admin/categories': typeof AppAdminCategoriesRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/employees': typeof AppAdminEmployeesRoute
  '/_app/admin/requests': typeof AppAdminRequestsRoute
  '/_app/admin/reviews': typeof AppAdminReviewsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/customer/dashboard': typeof AppCustomerDashboardRoute
  '/_app/employee/dashboard': typeof AppEmployeeDashboardRoute
  '/_app/employee/reviews': typeof AppEmployeeReviewsRoute
  '/_app/customer/requests/$id': typeof AppCustomerRequestsIdRoute
  '/_app/customer/requests/new': typeof AppCustomerRequestsNewRoute
  '/_app/employee/requests/$id': typeof AppEmployeeRequestsIdRoute
  '/_app/employee/requests/nearby': typeof AppEmployeeRequestsNearbyRoute
  '/_app/customer/requests/': typeof AppCustomerRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/profile'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/requests'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/dashboard'
    | '/employee/dashboard'
    | '/employee/reviews'
    | '/customer/requests/$id'
    | '/customer/requests/new'
    | '/employee/requests/$id'
    | '/employee/requests/nearby'
    | '/customer/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/profile'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/requests'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/dashboard'
    | '/employee/dashboard'
    | '/employee/reviews'
    | '/customer/requests/$id'
    | '/customer/requests/new'
    | '/employee/requests/$id'
    | '/employee/requests/nearby'
    | '/customer/requests'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/_app/profile'
    | '/_app/admin/categories'
    | '/_app/admin/dashboard'
    | '/_app/admin/employees'
    | '/_app/admin/requests'
    | '/_app/admin/reviews'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/customer/dashboard'
    | '/_app/employee/dashboard'
    | '/_app/employee/reviews'
    | '/_app/customer/requests/$id'
    | '/_app/customer/requests/new'
    | '/_app/employee/requests/$id'
    | '/_app/employee/requests/nearby'
    | '/_app/customer/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee/reviews': {
      id: '/_app/employee/reviews'
      path: '/employee/reviews'
      fullPath: '/employee/reviews'
      preLoaderRoute: typeof AppEmployeeReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee/dashboard': {
      id: '/_app/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof AppEmployeeDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customer/dashboard': {
      id: '/_app/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof AppCustomerDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reviews': {
      id: '/_app/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AppAdminReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/requests': {
      id: '/_app/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AppAdminRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees': {
      id: '/_app/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AppAdminEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/categories': {
      id: '/_app/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AppAdminCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customer/requests/': {
      id: '/_app/customer/requests/'
      path: '/customer/requests'
      fullPath: '/customer/requests/'
      preLoaderRoute: typeof AppCustomerRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee/requests/nearby': {
      id: '/_app/employee/requests/nearby'
      path: '/employee/requests/nearby'
      fullPath: '/employee/requests/nearby'
      preLoaderRoute: typeof AppEmployeeRequestsNearbyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee/requests/$id': {
      id: '/_app/employee/requests/$id'
      path: '/employee/requests/$id'
      fullPath: '/employee/requests/$id'
      preLoaderRoute: typeof AppEmployeeRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customer/requests/new': {
      id: '/_app/customer/requests/new'
      path: '/customer/requests/new'
      fullPath: '/customer/requests/new'
      preLoaderRoute: typeof AppCustomerRequestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customer/requests/$id': {
      id: '/_app/customer/requests/$id'
      path: '/customer/requests/$id'
      fullPath: '/customer/requests/$id'
      preLoaderRoute: typeof AppCustomerRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppAdminCategoriesRoute: typeof AppAdminCategoriesRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminEmployeesRoute: typeof AppAdminEmployeesRoute
  AppAdminRequestsRoute: typeof AppAdminRequestsRoute
  AppAdminReviewsRoute: typeof AppAdminReviewsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppCustomerDashboardRoute: typeof AppCustomerDashboardRoute
  AppEmployeeDashboardRoute: typeof AppEmployeeDashboardRoute
  AppEmployeeReviewsRoute: typeof AppEmployeeReviewsRoute
  AppCustomerRequestsIdRoute: typeof AppCustomerRequestsIdRoute
  AppCustomerRequestsNewRoute: typeof AppCustomerRequestsNewRoute
  AppEmployeeRequestsIdRoute: typeof AppEmployeeRequestsIdRoute
  AppEmployeeRequestsNearbyRoute: typeof AppEmployeeRequestsNearbyRoute
  AppCustomerRequestsIndexRoute: typeof AppCustomerRequestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppAdminCategoriesRoute: AppAdminCategoriesRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminEmployeesRoute: AppAdminEmployeesRoute,
  AppAdminRequestsRoute: AppAdminRequestsRoute,
  AppAdminReviewsRoute: AppAdminReviewsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppCustomerDashboardRoute: AppCustomerDashboardRoute,
  AppEmployeeDashboardRoute: AppEmployeeDashboardRoute,
  AppEmployeeReviewsRoute: AppEmployeeReviewsRoute,
  AppCustomerRequestsIdRoute: AppCustomerRequestsIdRoute,
  AppCustomerRequestsNewRoute: AppCustomerRequestsNewRoute,
  AppEmployeeRequestsIdRoute: AppEmployeeRequestsIdRoute,
  AppEmployeeRequestsNearbyRoute: AppEmployeeRequestsNearbyRoute,
  AppCustomerRequestsIndexRoute: AppCustomerRequestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
