// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Refresh if the access token expires within this many seconds.
const REFRESH_THRESHOLD_SECONDS = 60

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    let session = data.session

    if (session?.expires_at) {
      const secondsLeft = session.expires_at - Math.floor(Date.now() / 1000)
      if (secondsLeft <= REFRESH_THRESHOLD_SECONDS) {
        const { data: refreshed } = await supabase.auth.refreshSession()
        if (refreshed.session) session = refreshed.session
      }
    }

    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
